### ISSUE TITLE
Weekly Scrum - Feb 20-24, 2023

### ISSUE THREAD

**Issue by kfoxIsProgrammer** [SYSC4806-Group13/SYSC4806-Project#5]
Each week a group member should open a new issue called Weekly scrum – [date], then every team
member should add comments with their own contribution, i.e. their answers to the questions:

1. what have I done this week? (with link(s) to the relevant GitHub Issue(s))
2. what will I do next week? (with link(s) to the relevant GitHub Issue(s))
3. what is holding me back? (if applicable)

Expected length: 1-2 sentences per item

**Comment by kfoxIsProgrammer** [comment]
What I have done this week?
- I had looked at our project topic and voted for the Amazin Book store.
- I looked at the presentation topics as well. I vote for Topic 23 - since I found articles on how to deploy to Aws using Github actions.

What I will do next week?
- I plan to start creating the react-app and push it to the correct repo.
- I also might look into creating some issues and adding them to the kanban board.

Any blockers?
- Currently no major blockers.
- We should decide on our project topic and presentation topic soonish.

**Comment by Justgo13** [comment]
What I have done this week?

* I looked at our project topics and voted for the Amazin Book store.
* I voted for the presentation topic Authentication and Authorization.

What I will do next week?

* I also might look into creating some issues and adding them to the kanban board.

Any blockers?

Currently no major blockers.

**Comment by NosBos** [comment]
What I have done this week?

I looked at our project topics and ranked all project topics and had Amazin Book store as my number 1 option.
For presentation topic I voted for Topic 15 -  Client-side testing (jasmine, moka, etc)

What I will do next week?

I will begin looking into the database design to see what tables we will need to create our poject.

Any blockers?

Currently no major blockers.
