### ISSUE TITLE
Weekly Scrum - Mar 13 - 17

### ISSUE THREAD

**Issue by kfoxIsProgrammer** [SYSC4806-Group13/SYSC4806-Project#52]
Each week a group member should open a new issue called Weekly scrum – [date], then every team
member should add comments with their own contribution, i.e. their answers to the questions:

1. what have I done this week? (with link(s) to the relevant GitHub Issue(s))

2. what will I do next week? (with link(s) to the relevant GitHub Issue(s))

3. what is holding me back? (if applicable)

Expected length: 1-2 sentences per item

**Comment by kfoxIsProgrammer** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- I had started the user profile and workflow for becoming a seller issue https://github.com/SYSC4806-Group13/SYSC4806-Project/issues/50. As well as helping @NosBos to do his image upload issue https://github.com/SYSC4806-Group13/SYSC4806-Project/issues/38

what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- I will be continuing those tickets to make a pr
- I will be working on cleaning up api calls and returning meaningful info to the frontend for failed requests.https://github.com/SYSC4806-Group13/SYSC4806-Project/issues/51

what is holding me back? (if applicable)
- The 4th year poster fair has put us all back.

**Comment by Justgo13** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
* Still working on #49 jaccard distance
* Reviewed #15 
* Reviewed #47 
* Worked on ER diagrams and UML with Millan

what will I do next week? (with link(s) to the relevant GitHub Issue(s))
* Review PR
* Work on Jaccard distance

what is holding me back? (if applicable)
Fourth year project was a blocker

**Comment by NosBos** [comment]
- **What have I done this week**
  -   Completed #38
  -   Reviewed PRs
- **What will I do next week**
  -   Determine what last tasks are needed
- **Blockers**
  -   No

**Comment by MillanWang** [comment]
- **What have I done this week? (with link(s) to the relevant GitHub Issue(s))**
  - PR'd #56 for the cart system integration
- **What will I do next week? (with link(s) to the relevant GitHub Issue(s))**
  - General improvements to the cart system UI styling
- **What is holding me back? (if applicable)**
  - 4th year project poster fair took a lot of my time

**Comment by GolanHassin** [comment]
- **What have I done this week? (with link(s) to the relevant GitHub Issue(s))**
  - Finished #47.
  - Responded to pull requests #57 and #56 
  - Finished #48, up for pull request, but the Search bar is to be added 
  - Testing of other branches
  - Continue to write tests for the branches
- **What will I do next week? (with link(s) to the relevant GitHub Issue(s))**
  - Add a search bar to #48 
  - Add more tests to #48 and #47
- **What is holding me back? (if applicable)**
  - Nothing
