### ISSUE TITLE
Final Scrum - Mar 20 - Apr 5

### ISSUE THREAD

**Issue by kfoxIsProgrammer** [SYSC4806-Group13/SYSC4806-Project#65]
Each week a group member should open a new issue called Weekly scrum – [date], then every team
member should add comments with their own contribution, i.e. their answers to the questions:

1. what have I done this week? (with link(s) to the relevant GitHub Issue(s))

2. what will I do next week? (with link(s) to the relevant GitHub Issue(s))

3. What is holding me back? (if applicable)

Expected length: 1-2 sentences per item

**Comment by kfoxIsProgrammer** [comment]
1. We had our Milestone 2 presentation. 
- I updated the Readme.
- I checked for bugs
- fixed a bug where sellers page could be accessed without being a seller
-  My pr for https://github.com/SYSC4806-Group13/SYSC4806-Project/issues/50 was merged
-  My PR for individual Listings was merged https://github.com/SYSC4806-Group13/SYSC4806-Project/issues/60


2. Leaving this issue on todo https://github.com/SYSC4806-Group13/SYSC4806-Project/issues/51, its not 100% required

3. No blockers

**Comment by MillanWang** [comment]
- **What have I done this week? (with link(s) to the relevant GitHub Issue(s))**
  - Edited and submitted presentation video
  - Finished integration of image management system into the cart view #61 
  - Helped Jason with some debugging during the development of #49
  - Helped Golan with some debugging during the development of #59 
  - PR Reviews
- **What will I do next week? (with link(s) to the relevant GitHub Issue(s))**
  - We are now done
- **What is holding me back? (if applicable)**
  - None

**Comment by Justgo13** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
* Finished jaccard distance feature #49 
* Added unit test in java backend to test jaccard algorithm
* Added jest test for recommendation carousel rendering

what will I do next week? (with link(s) to the relevant GitHub Issue(s))
* Review PR
* Work on refactoring CSS so site looks nicer
* Add prettier formatter

What is holding me back? (if applicable)

**Comment by GolanHassin** [comment]
- **What have I done this week? (with link(s) to the relevant GitHub Issue(s))**
  - Worked on video
  - Worked on #59 
- **What will I do next week? (with link(s) to the relevant GitHub Issue(s))**
  - Continuing #59
  - PR reviews
- **What is holding me back? (if applicable)**
  - None

**Comment by NosBos** [comment]
* **What have I done this week? (with link(s) to the relevant GitHub Issue(s))**
  * Worked on video presentation
  * Worked on #69 
  * Milestone 3 UML diagrams
 * **What will I do next week? (with link(s) to the relevant GitHub Issue(s))**
   * PR reviews
   * We almost doneeee
* **What is holding me back? (if applicable)**
  * Nope
