### ISSUE TITLE
Weekly Scrum - Feb 27 - Mar 3

### ISSUE THREAD

**Issue by kfoxIsProgrammer** [SYSC4806-Group13/SYSC4806-Project#7]
Each week a group member should open a new issue called Weekly scrum – [date], then every team
member should add comments with their own contribution, i.e. their answers to the questions:

1. what have I done this week? (with link(s) to the relevant GitHub Issue(s))
2. what will I do next week? (with link(s) to the relevant GitHub Issue(s))
3. what is holding me back? (if applicable)

Expected length: 1-2 sentences per item

**Comment by kfoxIsProgrammer** [comment]
1. I have put in a lot of research and a [PR](https://github.com/MillanWang/SYSC4806-Project/pull/28) into including a security protocol for our spring boot application. The incorporation of the OAuth2 protocol with Google, allows us to save logins with Google. https://github.com/MillanWang/SYSC4806-Project/issues/10.

2. next week I plan to add the Axios library to our React application. This will be used for HTTP requests. Also, I plan to create the Logic for our React Application to know when a user is logged in. #9 

3. Blockers, I have found a hacky solution for testing our Backend application while it is protected by security. I'm not 100% sure how to unit-test all of the functionality that I have found though :P. therefore there is a some risk involved

**Comment by Justgo13** [comment]
1. I worked on setting up the front-end react project template using typescript #8 . I also worked on creating cards for the book listing that use dummy data #11 
2. I plan on working on the seller form and listing page #34 
3. Nothing is blocking me

**Comment by MillanWang** [comment]
1.
- Set up Spring environment in repository and CI pipeline #24 #19 
- Created endpoint for user cart and made reusable endpoint testing utility classes #17 
- PR Reviewed #26 #27 

2.
- Updating the cart API to join with Listings for responses, and updating exception system
- Potentially linking the frontend to API call the cart API 
- Potentially adding an endpoint for checking out the cart and simulating payments

3.
- No blockers

**Comment by NosBos** [comment]
1. 
* Created endpoint for listings along with error handling and integration testing #26 
* Helped setup intial backend project and planned database design with team
* Reviewed some PRs

2.
* Connect listings table to actually match to Users table
* Perhaps setup backend to support adding to cart

3. No blockers

**Comment by GolanHassin** [comment]
1. what have I done this week?
This first week was setting up the project and assigning the project responsibilities to each member

what will I do next week?
I will be working on my different responsibilities like setting a Post request from the listing URL 
what is holding me back?
